# Generated by Django 6.0.7 on 2026-07-30 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('kalikattan', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('chicken', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('kuboos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mandi', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pepsi', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bill', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sale', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('swiggy', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expense_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dailyexpense')),
            ],
        ),
    ]
