# Generated by Django 6.0.7 on 2026-07-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dailyexpense_dailytracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytracker',
            name='expense_record',
        ),
        migrations.AddField(
            model_name='dailytracker',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
