# Generated by Django 6.0.7 on 2026-08-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expense_income_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(default='Staff', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
