# Generated by Django 6.0.7 on 2026-08-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daily_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
