# Generated by Django 6.0.7 on 2026-09-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_role_salaryrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
