# Generated by Django 6.0.7 on 2026-09-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_inventoryitem_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
